apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.masterReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-master
        role: "master"
    spec:
      containers:
      - name: {{ .Chart.Name }}-master
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: "loc-master-web"
            containerPort: 8089
            protocol: "TCP"
          - name: "loc-master-p1"
            containerPort: 5557
            protocol: "TCP"
          - name: "loc-master-p2"
            containerPort: 5558
            protocol: "TCP"
        env:
          - name: "LOCUST_MODE"
            value: "master"
# Helm has a bug related to envFrom and configmaps, https://github.com/kubernetes/helm/issues/2257
# This should be moved to envFrom the configMap when that is possible
          {{- range $key, $val := .Values.locust_config_options }}
          - name: {{ $key }}
            value: {{ $val | quote}}
          {{- end}}
